version: '3.1'

services:
   mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sqlscripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password123
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - default
 
networks:
  default:        
    driver: bridge
      